### ISSUE TITLE
Feature to save your project to edit it later on.

### ISSUE THREAD

**Issue by RobijnGit** [grzybeek/grzyClothTool#13]
For example, an clothing pack has multiple high-heel shoes, hairs or different sounds for components, if I wish to add a new component or texture - I would have to set all those parameters again to the shoes, hairs and components because you need to re-import all the drawables.

To make it more user friendly, a simple project save and load would help a ton to make small changes actually fast and easy to do with this tool.

**Comment by RobijnGit** [comment]
Ah, this was recently implemented and I had not noticed it until just now. Lol.
Excuse me, will close.

**Comment by grzybeek** [comment]
Yes, I didn't want to implement it as a save, but rather ability to open any already existing addon 😄
