### ISSUE TITLE
Props wont load on "OpenAddon"

### ISSUE THREAD

**Issue by Caroliiiin** [grzybeek/grzyClothTool#15]
Version 0.0.9 Alpha
When loading the created addon, all props get removed.
p_head. p_ears, p_eyes, etc

and all shoes are automatically 1.0 high, even when they are not marked as heels they will be exported as heels.

**Comment by grzybeek** [comment]
hi thanks for report, it is already known (reported before on discord), will try to fix it for next versions

**Comment by grzybeek** [comment]
should be fixed in next release, not sure yet when, tool will automatically download new update
