### ISSUE TITLE
bug when loading autosaves

### ISSUE THREAD

**Issue by realCallMeJ** [grzybeek/grzyClothTool#17]
when loading an autosave, all drawables have the numbers in their names changed to 000
![image](https://github.com/grzybeek/grzyClothTool/assets/73816044/b3e6cbe5-5ef9-45dc-adda-2ae7a6ac302f)

**though, when adding a new drawable and then deleting it after, it will fix all the numbers**

**Comment by grzybeek** [comment]
Hi, thanks for report, it will be fixed in next release.

Feel free to join discord and report bugs here, it has all up to date info about bugs and what is already fixed (but not released yet)
![image](https://github.com/grzybeek/grzyClothTool/assets/40837847/04fb72e5-44df-4ee4-b3f9-d5ee7a8c2cae)
