### ISSUE TITLE
Green Textures on import or load hair's textures

### ISSUE THREAD

**Issue by Artzalez** [grzybeek/grzyClothTool#25]
When you import hairs textures, some textures bug to green color and size increase of texture.

![image](https://github.com/user-attachments/assets/7809bf1f-8c2b-4599-9a75-a8956dde229e)

And when build all texures green keep ingame.

**Comment by grzybeek** [comment]
This doesn't look as the same texture even. Please provide your files so I can reproduce it on my end, you can do it via discord DMs

**Comment by Artzalez** [comment]
The problem has been that when loading the meta the program has not maintained the order and when I checked my files they were not in the correct order.
