### ISSUE TITLE
Animation Issue

### ISSUE THREAD

**Issue by porterslug** [grzybeek/grzyClothTool#4]
I tried a lot and found this issue. If you try some cloth, a.e. vests (task) or shirts, hoodies (jbib) and try to start the animation sequence, the cloth acts like a prop and stays at its point or starts to float in the opposite direction.

**Comment by grzybeek** [comment]
Hi, I saw it multiple times, but after second try it worked for me, does it happen 100% times for you with certain models? If so, can you please send me those models on discord, you can find invite to join on readme

**Comment by grzybeek** [comment]
Closing, because no answer from author. If you have any models that always reproduce this issue, feel free to send me it on my discord
