### ISSUE TITLE
When 3D previewing Male Clothing, womens PED is shown.

### ISSUE THREAD

**Issue by BalesDot** [grzybeek/grzyClothTool#5]
WHen looking at some MC vests i made, tried 3D preview and instead of showing a male, it showed a female. 
![image](https://github.com/grzybeek/grzyClothTool/assets/125777160/daae8687-9bc1-4c27-852b-6c20e96cb7c9)

**Comment by grzybeek** [comment]
Not an issue, just not implemented feature yet. It is somewhere in my todo list, but not a priority because for now you can manually change ped if you expand menu on the left top corner
