### ISSUE TITLE
Head Props are not displayed correctly in 3D Preview

### ISSUE THREAD

**Issue by theskiratta** [grzybeek/grzyClothTool#6]
As stated in the title, when using the 3D preview for head props (p_head, p_eyes) won't show up on the head. Instead they show up at the side of the peds body. This is quite annoying when you're trying to see whether the hairscale you have is enough because you can't see whether the hair will actually clip through or not.

**Comment by grzybeek** [comment]
what do you mean? It works fine for me, you would need to send me broken files so I can reproduce it
![image](https://github.com/grzybeek/grzyClothTool/assets/40837847/81215914-c0e9-4bb3-896b-eb7aa65a35b1)

**Comment by Bushcowboy** [comment]
for  me  head props dont load  properly in  game and in 3d  view  they are at the players hip

**Comment by Bushcowboy** [comment]
![image](https://github.com/grzybeek/grzyClothTool/assets/87616296/a3c39a4b-7a9e-488e-9005-51765e919229)

**Comment by Bushcowboy** [comment]
wth 2 seconds later its proper

**Comment by grzybeek** [comment]
yeah it *might* sometimes happen, but usually it should be enough to just switch to different model and switch back to your prop

**Comment by Bushcowboy** [comment]
uhm so now it just does not load the  addon hats ingame

**Comment by grzybeek** [comment]
are you talking about SP or FiveM resource?
There is known bug in SP and I think they don't work at all - but FiveM should all work fine.

**Comment by Bushcowboy** [comment]
fivem

**Comment by grzybeek** [comment]
I don't know, it works fine for me. Maybe you are hitting total 255 prop limit

**Comment by Bushcowboy** [comment]
ohhhhhhhhhhhhhhhhhh yep thats 100%  it

**Comment by grzybeek** [comment]
User did not provide assets that reproduce this issue, closing
