### ISSUE TITLE
[Suggestion] Presets for Props

### ISSUE THREAD

**Issue by antho-444** [grzybeek/grzyClothTool#9]
Instead of having to turn on hair scale and change the value using the Up and Down arrow, you could have a button or something that automatically sets the value of 0.50 so hair does not clip thru hats and stuff. Keep up the good work tho!

**Comment by grzybeek** [comment]
I'm going to close this, because some time ago there was a change to make 0.5 default value. Should be enough for now, if not, feel free to reopen it
